stages:
  - build
  - update_helm_chart

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"
    - if: $CI_COMMIT_BRANCH == "production"
    - when: never

include:
  - local: '.gitlab-ci.staging.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "staging"
  - local: '.gitlab-ci.production.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "production"

dummy_job:
  stage: build
  script:
    - echo "Dummy job"
  rules:
    - when: never
